// import { Trips } from "./trips";


// export const TRIPS: Trips[] = [{
//     id: firstTrip,
//     destinationName: Tirana,
//     price: 350,
//     shortDescription: string,
//     dificulty: Moderate,
//     activity: Cultural,
//     rating: Array < Rating >,
//     location: Tirana,
//     mostPopular: true,
//     upComing: boolean,
//     imageCover: string,
//     reccomandations: string,
//     longDiscription: string,
//     itinerary: Array < Itinerary >,
// },
// {
//     id: string,
//     destinationName: string,
//     price: number,
//     shortDescription: string,
//     dificulty: string,
//     activity: string,
//     rating: Array < Rating >,
//     location: string,
//     mostPopular: boolean,
//     upComing: boolean,
//     imageCover: string,
//     reccomandations: string,
//     longDiscription: string,
//     itinerary: Array < Itinerary >,
// },
// {
//     id: string,
//     destinationName: string,
//     price: number,
//     shortDescription: string,
//     dificulty: string,
//     activity: string,
//     rating: Array < Rating >,
//     location: string,
//     mostPopular: boolean,
//     upComing: boolean,
//     imageCover: string,
//     reccomandations: string,
//     longDiscription: string,
//     itinerary: Array < Itinerary >,

// },
// {
//     id: string,
//     destinationName: string,
//     price: number,
//     shortDescription: string,
//     dificulty: string,
//     activity: string,
//     rating: Array < Rating >,
//     location: string,
//     mostPopular: boolean,
//     upComing: boolean,
//     imageCover: string,
//     reccomandations: string,
//     longDiscription: string,
//     itinerary: Array < Itinerary >,
// },
// {
//     id: string,
//     destinationName: string,
//     price: number,
//     shortDescription: string,
//     dificulty: string,
//     activity: string,
//     rating: Array < Rating >,
//     location: string,
//     mostPopular: boolean,
//     upComing: boolean,
//     imageCover: string,
//     reccomandations: string,
//     longDiscription: string,
//     itinerary: Array < Itinerary >,

// },
// {
//     id: string,
//     destinationName: string,
//     price: number,
//     shortDescription: string,
//     dificulty: string,
//     activity: string,
//     rating: Array < Rating >,
//     location: string,
//     mostPopular: boolean,
//     upComing: boolean,
//     imageCover: string,
//     reccomandations: string,
//     longDiscription: string,
//     itinerary: Array < Itinerary >,
// },
// {
//     id: string,
//     destinationName: string,
//     price: number,
//     shortDescription: string,
//     dificulty: string,
//     activity: string,
//     rating: Array < Rating >,
//     location: string,
//     mostPopular: boolean,
//     upComing: boolean,
//     imageCover: string,
//     reccomandations: string,
//     longDiscription: string,
//     itinerary: Array < Itinerary >,
// },
// {
//     id: string,
//     destinationName: string,
//     price: number,
//     shortDescription: string,
//     dificulty: string,
//     activity: string,
//     rating: Array < Rating >,
//     location: string,
//     mostPopular: boolean,
//     upComing: boolean,
//     imageCover: string,
//     reccomandations: string,
//     longDiscription: string,
//     itinerary: Array < Itinerary >,
// }
// ]